// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import health "github.com/atsu/goat/health"
import mock "github.com/stretchr/testify/mock"

// Signal is an autogenerated mock type for the Signal type
type Signal struct {
	mock.Mock
}

// RawReport provides a mock function with given fields: _a0
func (_m *Signal) RawReport(_a0 []byte) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Report provides a mock function with given fields: _a0, _a1
func (_m *Signal) Report(_a0 health.Event, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(health.Event, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
